// Mob Locations — which Hypixel SkyBlock zone/Bestiary tab each mob lives in, a separate
// dimension from lib/mobTypes.js's combat-type classification. Sourced from the wiki's
// Bestiary/List page (parsed from raw wikitext) plus a hand-mapped "Slayer" location for the
// bosses/Dungeon-only mobs the in-game Bestiary itself doesn't track — see
// docs/mob-types-reference.html for the full generation notes. 298 of MOB_TYPES' 322 mobs have
// a location; the remainder are Slayer-boss variants absent from both source wiki pages.
//
// The six Fishing-related Bestiary tabs are kept as separate "Sea Creatures - X" locations
// (Water/Lava/Spooky/Fishing Festival/Winter/Backwater Bayou) rather than one merged bucket, so
// e.g. "only show Lava Fishing mobs" is a real filter option.

export const MOB_LOCATIONS = {
  'Abyssal Miner': ['Sea Creatures - Water'],
  'Agarimoo': ['Sea Creatures - Water'],
  'Alligator': ['Sea Creatures - Backwater Bayou'],
  'Angry Archaeologist': ['The Catacombs'],
  'Apostle': ['The Catacombs'],
  'Arachne': ['Spider\'s Den'],
  'Arachne\'s Brood': ['Spider\'s Den'],
  'Arachne\'s Keeper': ['Spider\'s Den'],
  'Ashfang': ['Crimson Isle'],
  'Atoll Croaker': ['Lotus Atoll'],
  'Automaton': ['Crystal Hollows'],
  'Bal': ['Crystal Hollows'],
  'Banshee': ['Sea Creatures - Backwater Bayou'],
  'Barbarian Duke X': ['Crimson Isle'],
  'Bat': ['Private Island', 'The Catacombs'],
  'Bat Piñata': ['Spooky Festival'],
  'Bayou Sludge': ['Sea Creatures - Backwater Bayou'],
  'Beetle': ['The Garden'],
  'Bezal': ['Crimson Isle'],
  'Bladesoul': ['Crimson Isle'],
  'Blaze': ['Crimson Isle'],
  'Blazing Golem': ['Kuudra'],
  'Blight': ['Kuudra'],
  'Blue Jerry': ['Jerry\'s Workshop'],
  'Blue Ringed Octopus': ['Sea Creatures - Water'],
  'Blue Shark': ['Sea Creatures - Fishing Festival'],
  'Bogged': ['Galatea'],
  'Bonzo': ['The Catacombs'],
  'Bonzo (Phase 2)': ['The Catacombs'],
  'Boss Corleone': ['Crystal Hollows'],
  'Broodmother': ['Spider\'s Den'],
  'Butterfly': ['Crystal Hollows'],
  'Carrot King': ['Sea Creatures - Water'],
  'Catfish': ['Sea Creatures - Water'],
  'Cellar Spider': ['The Catacombs'],
  'Chaosmite': ['The Catacombs'],
  'Chicken': ['The Farming Islands'],
  'Chill': ['Galatea'],
  'Chillblade': ['Galatea'],
  'Chillshot': ['Galatea'],
  'Cow': ['The Farming Islands'],
  'Crazy Witch': ['Spooky Festival'],
  'Creeper': ['Private Island'],
  'Cretan Bull': ['Mythological'],
  'Cricket': ['The Garden'],
  'Crypt Dreadlord': ['The Catacombs'],
  'Crypt Ghoul': ['Hub'],
  'Crypt Lurker': ['The Catacombs'],
  'Crypt Souleater': ['The Catacombs'],
  'Crypt Undead': ['The Catacombs'],
  'Dasher Spider': ['Spider\'s Den'],
  'Deep Sea Protector': ['Sea Creatures - Water'],
  'Diamond Goblin': ['Dwarven Mines'],
  'Dragonfly': ['The Garden'],
  'Dropship': ['Kuudra'],
  'Drowned Captain': ['Lotus Atoll'],
  'Dumpster Diver': ['Sea Creatures - Backwater Bayou'],
  'Earthworm': ['The Garden'],
  'Emerald Slime': ['Deep Caverns'],
  'End Stone Protector': ['The End'],
  'Ender Dragon': ['The End'],
  'Enderman': ['Private Island', 'The End'],
  'Endermite': ['The End'],
  'Ent': ['Galatea'],
  'Explosive Imp': ['Kuudra'],
  'Fels': ['The Catacombs'],
  'Field Mouse': ['The Garden'],
  'Fiery Scuttler': ['Sea Creatures - Lava'],
  'Fire Eel': ['Sea Creatures - Lava'],
  'Firefly': ['The Garden'],
  'Fireproof Witch': ['Sea Creatures - Lava'],
  'Flaming Spider': ['Crimson Isle'],
  'Flaming Worm': ['Sea Creatures - Lava'],
  'Flare': ['Crimson Isle'],
  'Flint Skeleton': ['Spider\'s Den'],
  'Flipflopper': ['Lotus Atoll'],
  'Fly': ['The Garden'],
  'Fried Chicken': ['Sea Creatures - Lava'],
  'Frog Man': ['Sea Creatures - Water'],
  'Frog Prince': ['Lotus Atoll'],
  'Frosty': ['Sea Creatures - Winter'],
  'Frozen Steve': ['Sea Creatures - Winter'],
  'Gaia Construct': ['Mythological'],
  'Ghast': ['Crimson Isle'],
  'Ghost': ['Dwarven Mines'],
  'Glacite Bowman': ['Dwarven Mines'],
  'Glacite Caver': ['Dwarven Mines'],
  'Glacite Mage': ['Dwarven Mines'],
  'Glacite Mutt': ['Dwarven Mines'],
  'Glacite Walker': ['Dwarven Mines'],
  'Goblin': ['Dwarven Mines'],
  'Goblin Raiders': ['Dwarven Mines'],
  'Golden Ghoul': ['Hub'],
  'Golden Goblin': ['Dwarven Mines'],
  'Golden Jerry': ['Jerry\'s Workshop'],
  'Goldor': ['The Catacombs'],
  'Golem': ['The Catacombs'],
  'gorF': ['Lotus Atoll'],
  'Gravel Skeleton': ['Spider\'s Den'],
  'Graveyard Zombie': ['Hub'],
  'Great White Shark': ['Sea Creatures - Fishing Festival'],
  'Green Jerry': ['Jerry\'s Workshop'],
  'Grim Reaper': ['Sea Creatures - Spooky'],
  'Grinch': ['Sea Creatures - Winter'],
  'Grunt': ['Crystal Hollows'],
  'Guardian Defender': ['Sea Creatures - Water'],
  'Harpy': ['Mythological'],
  'Headless Horseman': ['Spooky Festival'],
  'Howling Spirit': ['The Park'],
  'Hydrospear': ['Galatea'],
  'Inferno Demonlord': ['Slayer'],
  'Inferno Magma Cube': ['Kuudra'],
  'Inkling': ['Sea Creatures - Water'],
  'Jumpin\' Jack': ['Sea Creatures - Spooky'],
  'Kada Knight': ['Crimson Isle'],
  'Key Guardian': ['Crystal Hollows'],
  'King Midas': ['The Catacombs'],
  'King Minos': ['Mythological'],
  'Kuudra Berserker': ['Kuudra'],
  'Kuudra Follower': ['Kuudra'],
  'Kuudra Knocker': ['Kuudra'],
  'Kuudra Landmine': ['Kuudra'],
  'Kuudra Slasher': ['Kuudra'],
  'Lapis Zombie': ['Deep Caverns'],
  'Lava Blaze': ['Sea Creatures - Lava'],
  'Lava Flame': ['Sea Creatures - Lava'],
  'Lava Leech': ['Sea Creatures - Lava'],
  'Lava Pigman': ['Sea Creatures - Lava'],
  'Littlefoot': ['Dwarven Mines'],
  'Livid': ['The Catacombs'],
  'Locust': ['The Garden'],
  'Lonely Spider': ['The Catacombs'],
  'Lord Jawbus': ['Sea Creatures - Lava'],
  'Lost Adventurer': ['The Catacombs'],
  'Lotum': ['Lotus Atoll'],
  'Lotus Guardian': ['Lotus Atoll'],
  'Lotusfish': ['Lotus Atoll'],
  'Lunar Moth': ['The Garden'],
  'Mage Outlaw': ['Crimson Isle'],
  'Magma Boss': ['Crimson Isle'],
  'Magma Cube': ['Crimson Isle'],
  'Magma Cube Rider': ['Crimson Isle'],
  'Magma Follower': ['Kuudra'],
  'Magma Pillar': ['Sea Creatures - Lava'],
  'Magma Slug': ['Sea Creatures - Lava'],
  'Manta Ray': ['Sea Creatures - Water'],
  'Manticore': ['Mythological'],
  'Matcho': ['Crimson Isle'],
  'Maxor': ['The Catacombs'],
  'Mega Bat': ['Spooky Festival'],
  'Millennia-Aged Blaze': ['Crimson Isle'],
  'Mimic': ['The Catacombs'],
  'Miner Skeleton': ['Deep Caverns'],
  'Miner Zombie': ['Deep Caverns'],
  'Minos Champion': ['Mythological'],
  'Minos Hunter': ['Mythological'],
  'Minos Inquisitor': ['Mythological'],
  'Minotaur': ['Mythological'],
  'Mite': ['The Garden'],
  'Mithril Grubber': ['Sea Creatures - Water'],
  'Moogma': ['Sea Creatures - Lava'],
  'Mosquito': ['The Garden'],
  'Moth': ['The Garden'],
  'Mushroom Bull': ['Crimson Isle'],
  'Mushroom Cow': ['The Farming Islands'],
  'Mutated Blaze': ['Crimson Isle'],
  'Necron': ['The Catacombs'],
  'Nessie': ['Galatea'],
  'Nest Endermite': ['The End'],
  'Nightmare': ['Sea Creatures - Spooky'],
  'Nurse Shark': ['Sea Creatures - Fishing Festival'],
  'Nutcracker': ['Sea Creatures - Winter'],
  'Oasis Rabbit': ['Sea Creatures - Water'],
  'Oasis Sheep': ['Sea Creatures - Water'],
  'Obsidian Defender': ['The End'],
  'Old Dragon': ['The End'],
  'Old Wolf': ['Hub'],
  'Pack Spirit': ['The Park'],
  'Phantom Fisher': ['Sea Creatures - Spooky'],
  'Phantom Spirit': ['Spooky Festival'],
  'Pig': ['The Farming Islands'],
  'Plhlegblast': ['Sea Creatures - Lava'],
  'Poisoned Water Worm': ['Sea Creatures - Water'],
  'Powder Ghast': ['Dwarven Mines'],
  'Praying Mantis': ['The Garden'],
  'Protector Dragon': ['The End'],
  'Puddle Jumper': ['Lotus Atoll'],
  'Purple Jerry': ['Jerry\'s Workshop'],
  'Pyroclastic Worm': ['Sea Creatures - Lava'],
  'Rabbit': ['The Farming Islands'],
  'Ragnarok': ['Sea Creatures - Lava'],
  'Rain Slime': ['Spider\'s Den'],
  'Rat': ['The Garden'],
  'Redstone Pigman': ['Deep Caverns'],
  'Reindrake': ['Sea Creatures - Winter'],
  'Revenant Horror': ['Slayer'],
  'Rider of the Deep': ['Sea Creatures - Water'],
  'Sadan': ['The Catacombs'],
  'Scarecrow': ['Sea Creatures - Spooky'],
  'Scarf': ['The Catacombs'],
  'Scared Skeleton': ['The Catacombs'],
  'Scary Jerry': ['Spooky Festival'],
  'Scatha': ['Crystal Hollows'],
  'Sea Archer': ['Sea Creatures - Water'],
  'Sea Guardian': ['Sea Creatures - Water'],
  'Sea Leech': ['Sea Creatures - Water'],
  'Sea Walker': ['Sea Creatures - Water'],
  'Sea Witch': ['Sea Creatures - Water'],
  'Seashine': ['Lotus Atoll'],
  'Seer': ['The End'],
  'Shadow Assassin': ['The Catacombs'],
  'Sheep': ['The Farming Islands'],
  'Shiny Pig': ['Hub'],
  'Siamese Lynxes': ['Mythological'],
  'Silverfish': ['Spider\'s Den'],
  'Skeleton': ['Private Island'],
  'Skeleton Grunt': ['The Catacombs'],
  'Skeleton Lord': ['The Catacombs'],
  'Skeleton Master': ['The Catacombs'],
  'Skeleton Soldier': ['The Catacombs'],
  'Skeletor': ['The Catacombs'],
  'Slime': ['Private Island'],
  'Sludge': ['Crystal Hollows'],
  'Slug': ['The Garden'],
  'Smoldering Blaze': ['Crimson Isle'],
  'Snapping Turtle': ['Sea Creatures - Water'],
  'Sneaky Creeper': ['Deep Caverns'],
  'Sniper': ['The Catacombs'],
  'Soul of the Alpha': ['The Park'],
  'Special Zealot': ['The End'],
  'Sphinx': ['Mythological'],
  'Spider': ['Private Island'],
  'Spider Jockey': ['Spider\'s Den'],
  'Spirit Bear': ['The Catacombs'],
  'Splitter Spider': ['Spider\'s Den'],
  'Squid': ['Sea Creatures - Water'],
  'Star Sentry': ['Dwarven Mines'],
  'Storm': ['The Catacombs'],
  'Stranded Nymph': ['Mythological'],
  'Stridersurfer': ['Galatea'],
  'Strong Dragon': ['The End'],
  'Super Archer': ['The Catacombs'],
  'Super Tank Zombie': ['The Catacombs'],
  'Superior Dragon': ['The End'],
  'Sven Packmaster': ['Slayer'],
  'Tadgang': ['Galatea'],
  'Tank Zombie': ['The Catacombs'],
  'Tarantula Broodfather': ['Slayer'],
  'Taurus': ['Sea Creatures - Lava'],
  'Tentacle': ['Crimson Isle'],
  'Terracotta': ['The Catacombs'],
  'Tewtil': ['Lotus Atoll'],
  'The Loch Emperor': ['Galatea'],
  'The Professor': ['The Catacombs'],
  'The Professor (Phase 2)': ['The Catacombs'],
  'The Watcher': ['The Catacombs'],
  'Thunder': ['Sea Creatures - Lava'],
  'Thyst': ['Crystal Hollows'],
  'Tidetot': ['Galatea'],
  'Tiger Shark': ['Sea Creatures - Fishing Festival'],
  'Timestalk Clone': ['The Garden'],
  'Titanoboa': ['Sea Creatures - Backwater Bayou'],
  'Trash Gobbler': ['Sea Creatures - Backwater Bayou'],
  'Treasure Hoarder': ['Dwarven Mines'],
  'Trick or Treater': ['Spooky Festival'],
  'Undead': ['The Catacombs'],
  'Undead Skeleton': ['The Catacombs'],
  'Unstable Dragon': ['The End'],
  'Vanquisher': ['Crimson Isle'],
  'Vittomite': ['Crystal Hollows'],
  'Voidgloom Seraph': ['Slayer'],
  'Voidling': ['The End'],
  'Voidling Extremist': ['The End'],
  'Voidling Fanatic': ['The End'],
  'Volcanic Snail': ['Sea Creatures - Lava'],
  'Voracious Spider': ['Spider\'s Den'],
  'Wandering Blaze': ['Kuudra'],
  'Water Hydra': ['Sea Creatures - Water'],
  'Water Worm': ['Sea Creatures - Water'],
  'Weaver Spider': ['Spider\'s Den'],
  'Werewolf': ['Sea Creatures - Spooky'],
  'Wetwing': ['Galatea'],
  'Wiki Tiki': ['Sea Creatures - Water'],
  'Wise Dragon': ['The End'],
  'Witch': ['Private Island'],
  'Wither Dragon': ['The Catacombs'],
  'Wither Gourd': ['Spooky Festival'],
  'Wither Guard': ['The Catacombs'],
  'Wither Husk': ['The Catacombs'],
  'Wither Miner': ['The Catacombs'],
  'Wither Sentry': ['Kuudra'],
  'Wither Skeleton': ['Crimson Isle'],
  'Wither Spectre': ['Crimson Isle'],
  'Withermancer': ['The Catacombs'],
  'Wolf': ['Hub'],
  'Worm': ['Crystal Hollows'],
  'Wraith': ['Spooky Festival'],
  'Yeti': ['Sea Creatures - Winter'],
  'Yog': ['Crystal Hollows'],
  'Young Dragon': ['The End'],
  'Zealot': ['The End'],
  'Zealot Bruiser': ['The End'],
  'Zombie': ['Private Island'],
  'Zombie Commander': ['The Catacombs'],
  'Zombie Grunt': ['The Catacombs'],
  'Zombie Knight': ['The Catacombs'],
  'Zombie Lord': ['The Catacombs'],
  'Zombie Soldier': ['The Catacombs'],
  'Zombie Villager': ['Hub'],
  'Zombuddy': ['The Garden'],
};

// Case-insensitive index, same convention as lib/mobTypes.js's LOOKUP.
const LOOKUP = new Map();
for (const [name, locations] of Object.entries(MOB_LOCATIONS)) {
  LOOKUP.set(name.toLowerCase(), locations);
}

export function getMobLocations(mobName) {
  const key = mobName.trim().toLowerCase();
  if (LOOKUP.has(key)) return LOOKUP.get(key);
  if (key.endsWith('s') && LOOKUP.has(key.slice(0, -1))) return LOOKUP.get(key.slice(0, -1));
  return [];
}

// Every location name, most-populous first — drives the filter chip order in TargetMobPicker.
const locationCounts = {};
for (const locations of Object.values(MOB_LOCATIONS)) {
  for (const loc of locations) locationCounts[loc] = (locationCounts[loc] || 0) + 1;
}
export const ALL_LOCATIONS = Object.keys(locationCounts).sort((a, b) => locationCounts[b] - locationCounts[a]);
export const LOCATION_COUNTS = locationCounts;
