// Mob Types — Hypixel Skyblock's in-game mob classification system (visible per-mob in the
// Bestiary). 322 mobs, merged from the wiki's Mob Types/List page and its Bestiary/List page —
// a mob missing from MOB_TYPES means undocumented, not typeless. Location (which Bestiary tab a
// mob lives in) is a separate dimension — see lib/mobLocations.js. A searchable reference table
// (the source this and mobLocations.js were generated from) lives at docs/mob-types-reference.html.
//
// Only 9 of the 23 types have a matching enchantment — see MOB_TYPE_ENCHANTS; the rest are
// flavor/lore classification only.

// Enchant id -> Mob Type(s) it grants bonus damage against. Keyed by the real NEU-REPO item
// id (lowercase), not display name — Woodsplitter's real id is the legacy "arcane".
export const ENCHANT_ID_MOB_TYPES = {
  smite: ['Undead', 'Skeletal', 'Wither'],
  ender_slayer: ['Ender'],
  bane_of_arthropods: ['Arthropod'],
  smoldering: ['Infernal'],
  cubism: ['Cubic'],
  impaling: ['Aquatic'],
  arcane: ['Woodland'],
};

export const MOB_TYPE_ENCHANTS = {
  Undead: 'Smite',
  Skeletal: 'Smite',
  Wither: 'Smite',
  Ender: 'Ender Slayer',
  Arthropod: 'Bane of Arthropods',
  Infernal: 'Smoldering',
  Cubic: 'Cubism',
  Aquatic: 'Impaling',
  Woodland: 'Woodsplitter',
};

export const MOB_TYPES = {
  'Abyssal Miner': ['Aquatic', 'Undead'],
  'Agarimoo': ['Animal', 'Aquatic'],
  'Alligator': ['Animal', 'Aquatic', 'Elusive'],
  'Angry Archaeologist': ['Humanoid', 'Subterranean', 'Boss'],
  'Apostle': ['Undead', 'Wither'],
  'Arachne': ['Arcane', 'Arthropod'],
  'Arachne\'s Brood': ['Arthropod'],
  'Arachne\'s Keeper': ['Arthropod'],
  'Ashfang': ['Arcane', 'Infernal', 'Boss'],
  'Atoll Croaker': ['Animal', 'Aquatic'],
  'Atoned Champion': ['Undead', 'Boss'],
  'Atoned Horror': ['Undead', 'Boss'],
  'Atoned Revenant': ['Undead', 'Boss'],
  'Automaton': ['Arcane', 'Construct', 'Subterranean'],
  'Bal': ['Cubic', 'Infernal', 'Shielded'],
  'Banshee': ['Aquatic', 'Humanoid'],
  'Barbarian Duke X': ['Humanoid', 'Animal', 'Boss'],
  'Bat': ['Airborne', 'Animal', 'Spooky'],
  'Bat Piñata': ['Airborne', 'Shielded', 'Spooky'],
  'Bayou Sludge': ['Aquatic', 'Cubic'],
  'Beetle': ['Pest'],
  'Bezal': ['Infernal'],
  'Bladesoul': ['Arcane', 'Skeletal', 'Wither', 'Boss'],
  'Blaze': ['Infernal'],
  'Blazing Golem': ['Construct', 'Infernal'],
  'Blight': ['Infernal', 'Undead'],
  'Blue Jerry': ['Humanoid', 'Shielded'],
  'Blue Ringed Octopus': ['Animal', 'Aquatic', 'Elusive'],
  'Blue Shark': ['Animal', 'Aquatic'],
  'Bogged': ['Aquatic', 'Skeletal'],
  'Bonzo': ['Arcane', 'Humanoid'],
  'Boss Corleone': ['Humanoid', 'Subterranean'],
  'Broodmother': ['Arthropod', 'Boss'],
  'Burningsoul Demon': ['Infernal', 'Boss'],
  'Butterfly': ['Airborne', 'Arcane', 'Subterranean'],
  'Carrot King': ['Animal', 'Aquatic'],
  'Catfish': ['Animal', 'Aquatic'],
  'Cellar Spider': ['Arthropod', 'Subterranean'],
  'Chaosmite': ['Arcane', 'Arthropod', 'Ender'],
  'Chicken': ['Animal'],
  'Chill': ['Skeletal', 'Woodland'],
  'Chillblade': ['Skeletal', 'Woodland'],
  'Chillshot': ['Skeletal', 'Woodland'],
  'Conjoined Brood': ['Arthropod', 'Boss'],
  'Cow': ['Animal'],
  'Crazy Witch': ['Shielded', 'Spooky'],
  'Creeper': ['Cubic'],
  'Cretan Bull': ['Animal', 'Mythological'],
  'Cricket': ['Pest'],
  'Crypt Dreadlord': ['Subterranean', 'Undead', 'Wither'],
  'Crypt Ghoul': ['Undead'],
  'Crypt Lurker': ['Undead'],
  'Crypt Souleater': ['Subterranean', 'Undead', 'Wither'],
  'Crypt Undead': ['Subterranean', 'Undead'],
  'Dasher Spider': ['Arthropod'],
  'Deep Sea Protector': ['Aquatic', 'Construct'],
  'Deformed Revenant': ['Undead', 'Boss'],
  'Diamond Goblin': ['Elusive', 'Humanoid', 'Shielded'],
  'Dragonfly': ['Pest'],
  'Dropship': ['Airborne', 'Arcane', 'Cubic'],
  'Drowned Captain': ['Aquatic', 'Undead'],
  'Dumpster Diver': ['Aquatic', 'Humanoid'],
  'Earthworm': ['Pest'],
  'Emerald Slime': ['Cubic'],
  'End Stone Protector': ['Construct', 'Ender'],
  'Ender Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Enderman': ['Ender'],
  'Endermite': ['Arthropod', 'Ender'],
  'Ent': ['Aquatic', 'Woodland'],
  'Explosive Imp': ['Infernal', 'Undead'],
  'Fels': ['Arcane'],
  'Field Mouse': ['Elusive', 'Pest'],
  'Fiery Scuttler': ['Animal', 'Elusive', 'Magmatic'],
  'Fire Eel': ['Animal', 'Magmatic'],
  'Firefly': ['Pest'],
  'Fireproof Witch': ['Arcane', 'Humanoid', 'Magmatic'],
  'Flaming Spider': ['Arthropod', 'Infernal'],
  'Flaming Worm': ['Arthropod', 'Magmatic'],
  'Flare': ['Infernal'],
  'Flare Demon': ['Infernal', 'Boss'],
  'Flint Skeleton': ['Skeletal'],
  'Flipflopper': ['Animal', 'Aquatic', 'Elusive'],
  'Fly': ['Pest'],
  'Fried Chicken': ['Animal', 'Magmatic'],
  'Frog Man': ['Animal', 'Aquatic', 'Humanoid'],
  'Frog Prince': ['Animal', 'Aquatic', 'Elusive'],
  'Frosty': ['Aquatic', 'Construct', 'Frozen'],
  'Frozen Adventurer': ['Humanoid', 'Frozen', 'Boss'],
  'Frozen Steve': ['Aquatic', 'Frozen', 'Humanoid'],
  'Gaia Construct': ['Construct', 'Mythological'],
  'Ghast': ['Airborne', 'Cubic'],
  'Ghost': ['Arcane', 'Subterranean'],
  'Glacite Bowman': ['Glacial', 'Humanoid'],
  'Glacite Caver': ['Glacial', 'Humanoid'],
  'Glacite Mage': ['Glacial', 'Humanoid'],
  'Glacite Mutt': ['Animal', 'Glacial'],
  'Glacite Walker': ['Glacial', 'Humanoid'],
  'Goblin': ['Humanoid', 'Subterranean'],
  'Goblin Raiders': ['Humanoid', 'Subterranean'],
  'Golden Ghoul': ['Undead'],
  'Golden Goblin': ['Humanoid', 'Shielded'],
  'Golden Jerry': ['Elusive', 'Humanoid', 'Shielded'],
  'Golem': ['Arcane', 'Construct'],
  'gorF': ['Animal', 'Aquatic', 'Arcane'],
  'Gravel Skeleton': ['Skeletal'],
  'Graveyard Zombie': ['Undead'],
  'Great White Shark': ['Animal', 'Aquatic', 'Elusive'],
  'Green Jerry': ['Humanoid', 'Shielded'],
  'Grim Reaper': ['Aquatic', 'Arcane', 'Spooky'],
  'Grinch': ['Aquatic', 'Construct', 'Frozen'],
  'Grunt': ['Humanoid'],
  'Guardian Defender': ['Aquatic', 'Arcane'],
  'Harpy': ['Animal', 'Humanoid', 'Mythological'],
  'Headless Horseman': ['Animal', 'Skeletal', 'Spooky', 'Undead'],
  'Howling Spirit': ['Animal', 'Arcane'],
  'Hydrospear': ['Aquatic', 'Undead', 'Woodland'],
  'Inferno Demonlord': ['Infernal', 'Boss'],
  'Inferno Magma Cube': ['Cubic', 'Infernal'],
  'Inkling': ['Animal', 'Aquatic'],
  'Jumpin\' Jack': ['Aquatic', 'Spooky'],
  'Kada Knight': ['Animal', 'Undead'],
  'Key Guardian': ['Subterranean', 'Undead'],
  'Kindleheart Demon': ['Infernal', 'Boss'],
  'King Midas': ['Humanoid', 'Boss'],
  'King Minos': ['Elusive', 'Humanoid', 'Mythological'],
  'Kuudra Berserker': ['Infernal', 'Undead'],
  'Kuudra Follower': ['Infernal', 'Undead'],
  'Kuudra Knocker': ['Infernal', 'Undead'],
  'Kuudra Landmine': ['Infernal', 'Undead'],
  'Kuudra Slasher': ['Cubic', 'Infernal'],
  'Lapis Zombie': ['Undead'],
  'Lava Blaze': ['Infernal', 'Magmatic'],
  'Lava Flame': ['Infernal', 'Magmatic'],
  'Lava Leech': ['Arthropod', 'Magmatic'],
  'Lava Pigman': ['Magmatic', 'Undead'],
  'Littlefoot': ['Elusive', 'Glacial', 'Humanoid'],
  'Locust': ['Pest'],
  'Lonely Spider': ['Arthropod'],
  'Lord Jawbus': ['Construct', 'Elusive', 'Magmatic'],
  'Lost Adventurer': ['Arcane', 'Humanoid', 'Boss'],
  'Lotum': ['Animal', 'Aquatic'],
  'Lotus Guardian': ['Aquatic', 'Construct'],
  'Lotusfish': ['Animal', 'Aquatic'],
  'Lunar Moth': ['Elusive', 'Pest'],
  'Mage Outlaw': ['Arcane', 'Humanoid'],
  'Magma Boss': ['Cubic', 'Infernal'],
  'Magma Cube': ['Cubic', 'Infernal'],
  'Magma Cube Rider': ['Cubic', 'Infernal', 'Undead'],
  'Magma Follower': ['Cubic', 'Infernal'],
  'Magma Pillar': ['Cubic', 'Magmatic'],
  'Magma Slug': ['Cubic', 'Magmatic'],
  'Manta Ray': ['Animal', 'Aquatic'],
  'Manticore': ['Animal', 'Elusive', 'Mythological'],
  'Matcho': ['Humanoid', 'Infernal'],
  'Mega Bat': ['Airborne', 'Shielded', 'Spooky'],
  'Millennia-Aged Blaze': ['Infernal', 'Subterranean'],
  'Mimic': ['Arcane', 'Construct', 'Undead'],
  'Miner Skeleton': ['Skeletal'],
  'Miner Zombie': ['Undead'],
  'Minos Champion': ['Humanoid', 'Mythological'],
  'Minos Hunter': ['Humanoid', 'Mythological', 'Undead'],
  'Minos Inquisitor': ['Elusive', 'Humanoid', 'Mythological'],
  'Minotaur': ['Humanoid', 'Mythological'],
  'Mite': ['Pest'],
  'Mithril Grubber': ['Aquatic', 'Arthropod'],
  'Moogma': ['Animal', 'Magmatic'],
  'Mosquito': ['Pest'],
  'Moth': ['Pest'],
  'Mushroom Bull': ['Animal'],
  'Mushroom Cow': ['Animal'],
  'Mutant Tarantula': ['Arthropod', 'Boss'],
  'Mutated Blaze': ['Infernal'],
  'Nessie': ['Animal', 'Aquatic', 'Elusive'],
  'Nest Endermite': ['Arthropod', 'Ender'],
  'Nightmare': ['Aquatic', 'Spooky', 'Undead'],
  'Nurse Shark': ['Animal', 'Aquatic'],
  'Nutcracker': ['Aquatic', 'Construct', 'Frozen'],
  'Oasis Rabbit': ['Animal', 'Aquatic'],
  'Oasis Sheep': ['Animal', 'Aquatic'],
  'Obsidian Defender': ['Ender', 'Wither'],
  'Old Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Old Wolf': ['Animal'],
  'Pack Enforcer': ['Animal', 'Boss'],
  'Pack Spirit': ['Animal', 'Arcane'],
  'Phantom Fisher': ['Aquatic', 'Arcane', 'Spooky'],
  'Phantom Spirit': ['Shielded', 'Spooky'],
  'Pig': ['Animal'],
  'Plhlegblast': ['Elusive', 'Magmatic'],
  'Poisoned Water Worm': ['Aquatic', 'Arthropod', 'Subterranean'],
  'Powder Ghast': ['Airborne', 'Cubic', 'Shielded'],
  'Praying Mantis': ['Pest'],
  'Protector Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Puddle Jumper': ['Animal', 'Aquatic', 'Elusive'],
  'Purple Jerry': ['Humanoid', 'Shielded'],
  'Pyroclastic Worm': ['Cubic', 'Magmatic'],
  'Quazii': ['Skeletal', 'Boss'],
  'Rabbit': ['Animal'],
  'Ragnarok': ['Elusive', 'Magmatic', 'Skeletal'],
  'Rain Slime': ['Cubic'],
  'Rat': ['Pest'],
  'Redstone Pigman': ['Undead'],
  'Redstone Warrior': ['Humanoid', 'Arcane', 'Boss'],
  'Reindrake': ['Elusive', 'Frozen', 'Shielded'],
  'Revenant Champion': ['Undead', 'Boss'],
  'Revenant Horror': ['Undead', 'Boss'],
  'Revenant Sycophant': ['Undead', 'Boss'],
  'Rider of the Deep': ['Animal', 'Aquatic', 'Undead'],
  'Scarecrow': ['Aquatic', 'Spooky'],
  'Scared Skeleton': ['Skeletal'],
  'Scary Jerry': ['Shielded', 'Spooky'],
  'Scatha': ['Elusive', 'Shielded', 'Subterranean'],
  'Sea Archer': ['Aquatic', 'Skeletal'],
  'Sea Guardian': ['Aquatic', 'Arcane'],
  'Sea Leech': ['Animal', 'Aquatic'],
  'Sea Walker': ['Aquatic', 'Undead'],
  'Sea Witch': ['Aquatic', 'Arcane', 'Humanoid'],
  'Seashine': ['Animal', 'Aquatic', 'Elusive'],
  'Seer': ['Ender'],
  'Shadow Assassin': ['Arcane', 'Humanoid', 'Boss'],
  'Sheep': ['Animal'],
  'Shiny Pig': ['Animal'],
  'Siamese Lynxes': ['Animal', 'Mythological'],
  'Silverfish': ['Arthropod'],
  'Skeleton': ['Skeletal'],
  'Skeleton Grunt': ['Skeletal'],
  'Skeleton Lord': ['Skeletal'],
  'Skeleton Master': ['Skeletal'],
  'Skeleton Soldier': ['Skeletal'],
  'Skeletor': ['Construct', 'Skeletal'],
  'Slime': ['Cubic'],
  'Sludge': ['Cubic', 'Subterranean'],
  'Slug': ['Pest'],
  'Smoldering Blaze': ['Infernal'],
  'Snapping Turtle': ['Animal', 'Aquatic'],
  'Sneaky Creeper': ['Cubic'],
  'Sniper': ['Skeletal', 'Undead'],
  'Soul of the Alpha': ['Animal', 'Arcane'],
  'Special Zealot': ['Elusive', 'Ender'],
  'Sphinx': ['Elusive', 'Humanoid', 'Mythological'],
  'Spider': ['Arthropod'],
  'Spider Jockey': ['Arthropod', 'Skeletal'],
  'Spirit Bear': ['Animal', 'Boss'],
  'Splitter Spider': ['Arthropod'],
  'Squid': ['Animal', 'Aquatic'],
  'Star Sentry': ['Arcane', 'Construct', 'Shielded'],
  'Stranded Nymph': ['Aquatic', 'Humanoid', 'Mythological'],
  'Stridersurfer': ['Magmatic', 'Undead', 'Woodland'],
  'Strong Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Super Archer': ['Skeletal'],
  'Super Tank Zombie': ['Undead'],
  'Superior Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Sven Alpha': ['Animal', 'Boss'],
  'Sven Follower': ['Animal', 'Boss'],
  'Sven Packmaster': ['Animal', 'Boss'],
  'Tadgang': ['Animal', 'Aquatic'],
  'Tank Zombie': ['Undead'],
  'Tarantula Beast': ['Arthropod', 'Boss'],
  'Tarantula Broodfather': ['Arthropod', 'Boss'],
  'Tarantula Vermin': ['Arthropod', 'Boss'],
  'Taurus': ['Animal', 'Humanoid', 'Magmatic'],
  'Tentacle': ['Cubic', 'Infernal'],
  'Terracotta': ['Arcane', 'Construct'],
  'Tewtil': ['Animal', 'Aquatic'],
  'The Loch Emperor': ['Aquatic', 'Arcane', 'Skeletal'],
  'The Watcher': ['Arcane', 'Boss'],
  'Thunder': ['Arcane', 'Elusive', 'Magmatic'],
  'Thyst': ['Arthropod', 'Subterranean'],
  'Tidetot': ['Aquatic', 'Undead', 'Woodland'],
  'Tiger Shark': ['Animal', 'Aquatic'],
  'Timestalk Clone': [],
  'Titanoboa': ['Animal', 'Aquatic', 'Elusive'],
  'Trash Gobbler': ['Aquatic', 'Arthropod'],
  'Treasure Hoarder': ['Humanoid', 'Subterranean'],
  'Trick or Treater': ['Shielded', 'Spooky'],
  'Typhoeus': ['Wither', 'Boss'],
  'Undead': ['Undead'],
  'Undead Skeleton': ['Skeletal', 'Undead'],
  'Unstable Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Vanquisher': ['Elusive', 'Wither'],
  'Vittomite': ['Arthropod', 'Ender'],
  'Voidcrazed Maniac': ['Ender', 'Boss'],
  'Voidgloom Seraph': ['Ender', 'Boss'],
  'Voidling': ['Ender'],
  'Voidling Devotee': ['Ender', 'Boss'],
  'Voidling Extremist': ['Ender'],
  'Voidling Fanatic': ['Ender'],
  'Voidling Radical': ['Ender', 'Boss'],
  'Volcanic Snail': ['Animal', 'Magmatic'],
  'Voracious Spider': ['Arthropod'],
  'Wandering Blaze': ['Infernal'],
  'Water Hydra': ['Animal', 'Aquatic', 'Elusive'],
  'Water Worm': ['Aquatic', 'Subterranean'],
  'Weaver Spider': ['Arthropod'],
  'Werewolf': ['Animal', 'Aquatic', 'Spooky'],
  'Wetwing': ['Animal', 'Aquatic', 'Undead'],
  'Wiki Tiki': ['Aquatic', 'Construct', 'Elusive'],
  'Wise Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Witch': ['Arcane', 'Humanoid'],
  'Wither Gourd': ['Shielded', 'Spooky'],
  'Wither Guard': ['Skeletal', 'Wither'],
  'Wither Husk': [],
  'Wither Miner': ['Skeletal', 'Wither'],
  'Wither Sentry': ['Construct', 'Wither'],
  'Wither Skeleton': ['Skeletal', 'Wither'],
  'Wither Spectre': ['Arcane', 'Wither'],
  'Withermancer': ['Arcane', 'Skeletal', 'Wither'],
  'Wolf': ['Animal'],
  'Worm': ['Shielded', 'Subterranean'],
  'Wraith': ['Shielded', 'Spooky'],
  'Yeti': ['Aquatic', 'Frozen', 'Humanoid'],
  'Yog': ['Cubic', 'Infernal', 'Subterranean'],
  'Young Dragon': ['Airborne', 'Arcane', 'Ender'],
  'Zealot': ['Ender'],
  'Zealot Bruiser': ['Ender'],
  'Zombie': ['Undead'],
  'Zombie Commander': ['Undead'],
  'Zombie Grunt': ['Undead'],
  'Zombie Knight': ['Undead'],
  'Zombie Lord': ['Undead'],
  'Zombie Soldier': ['Undead'],
  'Zombie Villager': ['Undead'],
  'Zombuddy': ['Shielded'],
};

// Fishing's own "Sea Creature" grouping (Flaming Flay/Soul Whip's real "Deals Nx damage to Sea
// Creatures" condition) — not a Mob Type, so it isn't in MOB_TYPES above; resolved as a name list
// instead (see conditionMatchesMob in lib/finalDamage.js). Coverage: only the ones also present in
// MOB_TYPES below can actually be picked as a target mob and match; the rest are real Sea
// Creatures this app's mob roster doesn't cover yet.
export const SEA_CREATURE_MOBS = [
  'Squid', 'Sea Walker', 'Sea Witch', 'Sea Archer', 'Rider of the Deep', 'Catfish', 'Sea Leech',
  'Guardian Defender', 'Deep Sea Protector', 'Water Hydra', 'Trash Gobbler', 'Dumpster Diver',
  'Banshee', 'Bayou Sludge', 'Alligator', 'Titanoboa', 'Atoll Croaker', 'Lotus Guardian', 'gorF',
  'Drowned Captain', 'Puddle Jumper', 'Frog Prince', 'Bogged', 'Wetwing', 'Tadgang', 'Ent',
  'Stridersurfer', 'The Loch Emperor', 'Nessie', 'Fried Chicken', 'Volcanic Snail',
  'Fireproof Witch', 'Magma Slug', 'Moogma', 'Lava Leech', 'Pyroclastic Worm', 'Magma Pillar',
  'Lava Flame', 'Fire Eel', 'Taurus', 'Thunder', 'Fiery Scuttler', 'Lord Jawbus', 'Ragnarok',
  'Frozen Steve', 'Frosty', 'Grinch', 'Nutcracker', 'Yeti', 'Reindrake', "Jumpin' Jack",
  'Scarecrow', 'Nightmare', 'Werewolf', 'Phantom Fisher', 'Grim Reaper', 'Nurse Shark',
  'Blue Shark', 'Tiger Shark', 'Great White Shark', 'Frog Man', 'Inkling', 'Snapping Turtle',
  'Manta Ray', 'Blue Ringed Octopus', 'Wiki Tiki', 'Mithril Grubber', 'Oasis Sheep',
  'Oasis Rabbit', 'Carrot King', 'Agarimoo', 'Water Worm', 'Poisoned Water Worm', 'Flaming Worm',
  'Lava Blaze', 'Lava Pigman', 'Abyssal Miner', 'Plhlegblast',
];

// Case-insensitive index built once at module load, since item lore/enchant text often uses pluralized or differently-cased mob names.
const LOOKUP = new Map();
for (const [name, types] of Object.entries(MOB_TYPES)) {
  LOOKUP.set(name.toLowerCase(), types);
}

// Strips a trailing "s" only when the singular form is a known mob name (e.g. "Zombies" -> "Zombie").
export function resolveMobKey(name) {
  const key = name.trim().toLowerCase();
  if (LOOKUP.has(key)) return key;
  if (key.endsWith('s') && LOOKUP.has(key.slice(0, -1))) return key.slice(0, -1);
  return null;
}

export function getMobTypes(mobName) {
  const key = resolveMobKey(mobName);
  return key ? LOOKUP.get(key) : [];
}

export function mobHasType(mobName, type) {
  return getMobTypes(mobName).includes(type);
}

export function getEnchantForType(type) {
  return MOB_TYPE_ENCHANTS[type] || null;
}
